# docker-compose build
version: '3'

services:
  postgre_db:
    image: kartoza/postgis:11.5-2.8
    container_name: postgre
    volumes:
      - ./pg_data:/var/lib/postgresql
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    env_file:
      - pg.env
    ports:
      - 5432:5432
    restart: always
    healthcheck:
      test: "exit 0"

networks:
  default:
    external:
      name: diplom
