# docker-compose build
version: '3.1'

services:
  osm2pgsql:
    # https://github.com/openfirmware/docker-osm2pgsql
    image: openfirmware/osm2pgsql
    container_name: osm2pgsql
    command: |
      osm2pgsql --create --slim --cache 2000 --database $PG_ENV_OSM_DB --username $PG_ENV_OSM_USER --host pg --port 5432 /osm/extract.osm.pbf
    links:
      - postgre_db:pg
    volumes:
      - ./osm:/osm openfirmware/osm2pgsql
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - PG_ENV_OSM_DB=gis
      - PG_ENV_OSM_USER=${POSTGRES_USER:-docker}
      - POSTGRES_PASS=${POSTGRES_PASS:-docker}
    restart: on-failure
    healthcheck:
      test: "exit 0"

networks:
  default: